[package]
name = "gql_codegen_config"
authors.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
gql_codegen_generators = { workspace = true }

serde = { workspace = true }
serde_json = { workspace = true }
