/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Result of code generation */
export interface GenerateResult {
  /** Whether generation was skipped (cache hit) */
  fresh: boolean
  /** Generated files (only populated if not fresh) */
  files: Array<GeneratedFile>
  /** Warnings encountered during generation */
  warnings: Array<string>
}
export interface GeneratedFile {
  path: string
  content: string
}
/** Options for the generate function */
export interface GenerateOptions {
  /** JSON string of the config */
  configJson: string
  /** Whether to skip caching */
  noCache?: boolean
  /** Whether to enable timing output */
  timing?: boolean
  /** Max diagnostics to show per error group (0 = unlimited, default 3) */
  maxDiagnostics?: number
}
/** Generate TypeScript types from GraphQL schema and operations */
export declare function generate(options: GenerateOptions): GenerateResult
/** Result of writing files to disk */
export interface WriteFilesResult {
  /** Paths that were written */
  written: Array<string>
  /** Paths skipped because content already matched */
  skipped: Array<string>
  /** Paths that failed to write, with error messages */
  errors: Array<WriteError>
}
export interface WriteError {
  path: string
  message: string
}
/**
 * Write generated files to disk using parallel I/O.
 *
 * Uses Rayon for parallel writes and skips files whose content already matches,
 * avoiding unnecessary filesystem events (useful for watch mode).
 */
export declare function writeFiles(files: Array<GeneratedFile>): WriteFilesResult
/** Clear the cache directory */
export declare function clearCache(baseDir: string): boolean
