[package]
name = "gql_codegen_js"
authors.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
gql_codegen_types = { workspace = true }

oxc = { workspace = true }
