/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Result of code generation */
export interface GenerateResult {
  /** Whether generation was skipped (cache hit) */
  fresh: boolean
  /** Generated files (only populated if not fresh) */
  files: Array<GeneratedFile>
  /** Warnings encountered during generation */
  warnings: Array<string>
}
export interface GeneratedFile {
  path: string
  content: string
}
/** Options for the generate function */
export interface GenerateOptions {
  /** JSON string of the config */
  configJson: string
  /** Whether to skip caching */
  noCache?: boolean
  /** Whether to enable timing output */
  timing?: boolean
}
/** Generate TypeScript types from GraphQL schema and operations */
export declare function generate(options: GenerateOptions): GenerateResult
/** Clear the cache directory */
export declare function clearCache(baseDir: string): boolean
